version: '3.1'

services:
  sc-api:
    container_name: sc-api
    depends_on:
      - mdb
      - rdb
    links:
      - mdb
      - rdb
    build:
      context: packages/server
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./packages/server:/usr/app/server
      - /usr/app/server/node_modules
    ports:
      - '4003:3003'
  sc-client:
    container_name: sc-client
    depends_on:
      - sc-api
    links:
      - sc-api
    build:
      context: packages/client
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./packages/client:/usr/app/client
      - /usr/app/client/node_modules
    ports:
      - '4004:3004'
  mdb:
    container_name: mdb
    image: mongo:4.0
    ports:
      - '27017:27017'
    volumes:
      - ./docker/data/db:/var/lib/mongo
  rdb:
    container_name: rdb
    image: redis:alpine
    hostname: rdb
    ports:
      - '6379:6379'
    volumes:
      - ./docker/data/db:/var/lib/redis
