export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CANCEL_MEMBER_INVITATION_API = 'CancelMemberInvitationAPI';
export const CHANGE_PASSWORD_API = 'ChangePasswordAPI';
export const CHECK_TOKEN_RESET_PASSWORD_API = 'CheckTokenResetPasswordAPI';
export const CREATE_DEPOSIT_ADDRESS_API = 'CreateDepositAddressAPI';
export const CREATE_PARTNER_NEW_WALLET_API = 'CreatePartnerNewWalletAPI';
export const DELIVER_ORDER_API = 'DeliverOrderAPI';
export const EDIT_USER_INFO_API = 'EditUserInfoAPI';
export const FORGOT_PASSWORD_API = 'ForgotPasswordAPI';
export const GET_ACCOUNT_SETTING_API = 'GetAccountSettingAPI';
export const GET_ALL_COINS_API = 'GetAllCoinsAPI';
export const GET_ALL_PAYMENTS_API = 'GetAllPaymentsAPI';
export const GET_ALL_PRODUCTS_API = 'GetAllProductsAPI';
export const GET_BILL_DETAILS_API = 'GetBillDetailsAPI';
export const GET_CURRENT_USER_API = 'GetCurrentUserAPI';
export const GET_MEMBER_LIST_API = 'GetMemberListAPI';
export const GET_MY_WALLETS_API = 'GetMyWalletsAPI';
export const GET_PAID_PARTNER_DETAILS_API = 'GetPaidPartnerDetailsAPI';
export const GET_PARTNER_MEMBER_DETAILS_API = 'GetPartnerMemberDetailsAPI';
export const GET_QUICK_FILTER_BILLS_API = 'GetQuickFilterBillsAPI';
export const GET_QUICK_FILTER_PAYMENTS_LIST_API =
  'GetQuickFilterPaymentsListAPI';
export const GET_QUICK_FILTER_TRANSACTIONS_API =
  'GetQuickFilterTransactionsAPI';
export const GET_QUICK_FILTER_PENDING_TRANSACTIONS_API =
  'GetQuickFilterPendingTransactionsAPI';
export const GET_RECEIVED_USER_DETAILS_API = 'GetReceivedUserDetailsAPI';
export const PAY_HEIAU_API = 'PayHeiauAPI';
export const PAY_TO_PARTNER_API = 'PayToPartnerAPI';
export const REGISTER_MEMBER_USER_API = 'RegisterMemberUserAPI';
export const REGISTER_PARTNER_USER_API = 'RegisterPartnerUserAPI';
export const RESET_PASSWORD_API = 'ResetPasswordAPI';
export const REVERT_ORDER_API = 'RevertOrderAPI';
export const SEND_TO_USER_API = 'SendToUserAPI';
export const UPDATE_ACCOUNT_SETTING_API = 'UpdateAccountSettingAPI';
export const VERIFY_PASSWORD_API = 'VerifyPasswordAPI';
export const INIT_SECRET_KEY_2FA_API = 'InitSecretKey2FAAPI';
export const VERIFY_AUTH_CODE_2FA_API = 'VerifyAuthCode2FAAPI';
export const GET_STATE_ENABLE_2FA_API = 'GetStateEnable2FAAPI';
export const SET_STATE_ENABLE_2FA_API = 'SetStateEnable2FAAPI';
export const GET_WITHDRAW_TX_INFO_API = 'GetWithdrawTxInfoAPI';
export const APPROVE_PENDING_TRANSACTION_API = 'ApprovePendingTransactionAPI';
export const REJECT_PENDING_TRANSACTION_API = 'RejectPendingTransactionAPI';
export const MANUAL_TRANSACTION_API = 'ManualTransactionAPI';

export default {
  APPROVE_PENDING_TRANSACTION_API,
  CHANGE_LANGUAGE,
  CANCEL_MEMBER_INVITATION_API,
  CHANGE_PASSWORD_API,
  CHECK_TOKEN_RESET_PASSWORD_API,
  CREATE_DEPOSIT_ADDRESS_API,
  CREATE_PARTNER_NEW_WALLET_API,
  DELIVER_ORDER_API,
  EDIT_USER_INFO_API,
  FORGOT_PASSWORD_API,
  GET_ACCOUNT_SETTING_API,
  GET_ALL_COINS_API,
  GET_ALL_PAYMENTS_API,
  GET_ALL_PRODUCTS_API,
  GET_BILL_DETAILS_API,
  GET_CURRENT_USER_API,
  GET_MEMBER_LIST_API,
  GET_MY_WALLETS_API,
  GET_PAID_PARTNER_DETAILS_API,
  GET_PARTNER_MEMBER_DETAILS_API,
  GET_QUICK_FILTER_BILLS_API,
  GET_QUICK_FILTER_PAYMENTS_LIST_API,
  GET_QUICK_FILTER_TRANSACTIONS_API,
  GET_QUICK_FILTER_PENDING_TRANSACTIONS_API,
  GET_RECEIVED_USER_DETAILS_API,
  GET_WITHDRAW_TX_INFO_API,
  PAY_HEIAU_API,
  PAY_TO_PARTNER_API,
  REGISTER_MEMBER_USER_API,
  REGISTER_PARTNER_USER_API,
  REJECT_PENDING_TRANSACTION_API,
  RESET_PASSWORD_API,
  REVERT_ORDER_API,
  SEND_TO_USER_API,
  UPDATE_ACCOUNT_SETTING_API,
  VERIFY_PASSWORD_API,
  INIT_SECRET_KEY_2FA_API,
  VERIFY_AUTH_CODE_2FA_API,
  GET_STATE_ENABLE_2FA_API,
  SET_STATE_ENABLE_2FA_API,
  MANUAL_TRANSACTION_API
};
